### ISSUE TITLE
[When attempting to reprint from history, there doesn't appear to be a way to select which printer is used for the reprint.] Handy Reprint, unable to select printer

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/Bambu-Handy#56]
When attempting to reprint from history with multiple printers in the account, there doesn't appear to be a way to select which printer is used for the reprint.
Appears to be using first/default printer, even if the print was previously sliced and completed on the second/other printer.

**Comment by werewolfenn** [comment]
Yes, seeing the same.  I'll see a single printer, not all that are available / online.  The available printer never changes.  No option to cycle through them.

**Comment by bolsoncerrado** [comment]
Same here.

**Describe the bug**
Can't reprint from History to specific printer On a multiple printer setup.

**3mf File for This Bug**
Happens with any file. 

**To Reproduce**
Unsure fully how to reproduce. 

I open the Handy app on Android OS. One of 3 printers available. I click on History, a print job, then try to Reprint but I can't choose the available printer. Instead I get a busy printer listed and no option to choose any other. 


**Expected behavior**
An actual list of available printers to choose a reprint to. 

**Screenshots**

![Screenshot_20230117-204229_Bambu Handy](https://user-images.githubusercontent.com/10992914/213023100-4f87c3b8-5112-4002-b581-f9db50284da4.jpg)
![Screenshot_20230117-204257_Bambu Handy](https://user-images.githubusercontent.com/10992914/213023105-677e265e-18a0-49c6-b335-3836b6f6f1e3.jpg)


**Desktop (please complete the following information):**
 - OS: Android OS 
 - Version latest

**Comment by mariskalejs** [comment]
Solution - remove from electricity all other printers .. ;)

**Comment by ab3dgeek** [comment]
same issue here, drives me up the wall sometimes....

**Comment by LibaoBambu** [comment]
Feature has been supported.
